### PR TITLE
Updating package.json to support the new grunt version 1.0.1

### PR DESCRIPTION
**Pull request by vanam**
Updating package.json to support the new grunt version 1.0.1 also changing the version of the package.json for transparency.

### CODE REVIEW

**Comment by fatso83** [comment]
On a trip to Japan so won't be publishing this to NPM until May 8th. You might want to remind me in three weeks :-)

**Comment by vanam** [comment]
@fatso83 Reminder :)

**Comment by fatso83** [comment]
ah, good one! totally forgot!

**Comment by fatso83** [comment]
Version 1.2.0 is out. I wasn't paying attention when merging this as I was in holiday-mode, but please bear in mind that there is no reason to touch the version number in a PR in 99% of all open-source projects. Reason being that there might be other PRs, or there might be versioning scripts that might want to tag the release in git, etc. I am using the default `npm version` task for instance to do this for me.

**Pull request merged**
